services:
  ProjectRPG:
    container_name: projectrpg
    image: teuspolec/projectrpg
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://projectrpg_db:3306/projectrpg?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=ProjectRPG
      - SPRING_DATASOURCE_PASSWORD=ProjectRPG
    ports:
      - "8080:8080"
    networks:
      - ProjectRPG-network
    depends_on:
      - projectrpg_db
    restart: on-failure

  ProjectRPG_angular:
    container_name: projectrpg_angular
    image: teuspolec/projectrpg_angular
    ports:
      - "4200:80"
    networks:
      - ProjectRPG-network
    depends_on:
      - projectrpg_db
    restart: on-failure

  projectrpg_db:
    container_name: mysqldb-server
    image: mysql
    ports:
      - 3306:3306
    restart: on-failure
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: projectrpg
      MYSQL_USER: ProjectRPG
      MYSQL_PASSWORD: ProjectRPG
      MYSQL_ROOT_PASSWORD: ProjectRPG
      MYSQL_ROOT_HOST: '%'
    networks:
      - ProjectRPG-network

networks:
  ProjectRPG-network:
    driver: bridge